### PR TITLE
Fixed typographical error, changed architechture to architecture in README.

### PR DESCRIPTION
**Pull request by orthographic-pedant**
@eBay, I've corrected a typographical error in the documentation of the [restcommander](https://github.com/eBay/restcommander) project. You should be able to merge this pull request automatically. However, if this was intentional or if you enjoy living in linguistic squalor, please let me know and [create an issue](https://github.com/thoppe/orthographic-pedant/issues/new) on my home repository.

### CODE REVIEW

**Comment by jeffpeiyt** [comment]
Thanks orthographic-pedant for your contribution. Thanks!

**Comment by jeffpeiyt** [comment]
somehow I cannot merge them as the repo you come from is gone.  I will make the change directly

**Comment by thoppe** [comment]
@jeffpeiyt That's interesting. I delete the repo as soon as the pull request is made. A few hundred other people have been able to make the merge successfully and yet and handle of them, like yourself, have this problem. If you have any insight into this please open up an issue!

**Comment by thoppe** [comment]
I think I see the problem. It happens if the issue is closed before a merge. Since the goal is to serve as a public service anyways, I'm OK if I don't get the commit record. Thanks!

**Comment by jeffpeiyt** [comment]
@thoppe  Thanks Travis again for your support! We are planning a release of Commander as a core library in a month with almost 50% rewriting code and tons of new features, plus 85% test coverage. Most importantly with the new library we restructure it so that ebay/internal are no longer two branches.
 We learned a lot from the experience.  Will keep you posted on the new one :-)

**Pull request closed without merging**
